### ISSUE TITLE
Running make throws error related to "requirements.txt"

### ISSUE THREAD

**Issue by erwald** [boris-tschirschwitz/create_project#1]
```zsh
$ gcl https://github.com/boris-tschirschwitz/create_project.git
Cloning into 'create_project'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 83 (delta 40), reused 67 (delta 24), pack-reused 0
Unpacking objects: 100% (83/83), done.

$ cd create_project

$ make
make: *** No rule to make target `requirements.txt', needed by `env/.requirements.lastrun'.  Stop.
```

or am I doing something wrong, perhaps?

**Comment by boris-tschirschwitz** [comment]
You just put it in the folder where you want to create the new project folder and call it with, e.g. if you want to pull the Kaggle titanic project, with
python create_project titanic -k
(I haven't looked into whether something needs to be done to make it work if create_project is just in the path)

So, you never call make directly in the create_project folder, it's just in ether to be copied over.

**Comment by erwald** [comment]
Gotcha, thanks!
